version: '3'
services:
  mysql:
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network



  prestashop:
    container_name: prestashop
    volumes:
      - psdata:/var/www/html
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network

volumes:
  dbdata:
  psdata:

networks:
  prestashop_network:
